# 第5章 语句

## 5.1 简单语句

简单语句，即末尾加上分号的表达式语句。

空语句：`;`，即一个分号，如`while(cin >> s && s != sought);`



## 5.3 条件语句

### 5.3.1 if语句

`else if`叫嵌套if语句

### 5.3.2 switch语句

case标签必须是整型常量表达式，且任意两个case标签值不能相同。

如果某个case匹配成功，将从该标签开始往后顺序执行所有case分支，除非显示地中断这一过程。

大多时候需要break语句，但有时候默认地switch行为是程序真正需要的，如***希望两个或多个值共享一组操作***。

```c++
switch (ch) {
    case 'a':
    case 'b';
    case 'c':
        ++cnt;
        break;
}
```



## 5.4 迭代语句

while、for、范围for、do while

定义在while条件部分或者while循环体内的变量每次迭代都要经历从创建到销毁的过程。



## 5.6 异常

异常处理机制包括：

- ***throw*** 异常检测部分使用throw在try中抛出异常
- ***try catch***异常处理代码
- 一套***异常类***（exception class) throw和catch之间传递异常的具体信息

***注意：throw后可以跟任意类型，不一定非要使用标准异常，但推荐使用标准异常。catch语句的异常声明与throw一致时才会走对应的分支！！！***

```c++
void func_throw(int flag)
{
	switch (flag) {
	case 0:
		throw int(0);
	case 1:
		throw string("string 1");
    case 2:
        throw std::exception("std exception");
	default:
		cout << "none error" << endl;
		break;
	}
}

int main()
{

	try {
		func_throw(0);
	}
	catch (const string& str) {
		cout << "string value: " << str << endl;
	}
	catch (const int& value) {
		cout << "int value:" << value << endl;
	}
    catch (const std::exceptrion &error) {
        cout << error.what() << endl;
    }
}
```

执行`func_throw(0)`抛出的异常是带整型参数，所以`catch`的`const int &value`会捕获到此异常；`func_throw(1)`同理。如果抛出了一个异常而没有被`catch`语句捕获，程序转到名为***terminate***的标准库函数，一般情况下该函数将导致程序非正常退出。

***标准异常***

`exception`是最基本的标准异常，使用`exception(const char *)`构造即可。再记住一个`runtime_error`。